# Generated by Django 2.2.7 on 2019-12-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191205_1142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
