# Generated by Django 2.2.7 on 2019-12-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
