# Generated by Django 2.2.7 on 2019-12-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_user',
        ),
    ]
