# Generated by Django 2.2.7 on 2019-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_post_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_user',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
