# Generated by Django 2.2.7 on 2019-12-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_user',
        ),
    ]
