# Generated by Django 2.2.7 on 2019-12-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_user',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
