# Generated by Django 2.2.7 on 2019-12-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_post_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
