# Generated by Django 2.2.7 on 2019-12-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20191223_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
